### ISSUE TITLE
Foreign business - Employment address block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1420] opened 2017-06-13 20:04 UTC
Change location block to City, State, Zip, and Country only

<img width="965" alt="screen shot 2017-06-13 at 4 01 05 pm" src="https://user-images.githubusercontent.com/19935974/27102062-e9a854a2-5051-11e7-99a0-8396c70e3aca.png">

![screen shot 2017-06-13 at 4 01 18 pm](https://user-images.githubusercontent.com/19935974/27102222-70d2e7ee-5052-11e7-9d95-e8b5d7da04dc.png)

**Comment by bmallred** [comment] 2017-06-14 15:59
@Jay-Neighbours-I72 We don't have one for this situation... does this need to be in the layout similar to the full address or more like a the birthplace usage?

**Comment by lauraponce** [comment] 2017-06-27 19:49
The form says city and state + zip **or** country. What I'm seeing here is country, city, state and zip if in the U.S. and country and city if it's outside the U.S. 

Should the fields be the same if it's inside the U.S. or outside? @billy22g @Jay-Neighbours-I72 

Also the placeholder text for the country box for outside the U.S. will need to be updated since it references place of birth. Thoughts?

![screen shot 2017-06-27 at 3 36 19 pm](https://user-images.githubusercontent.com/21222704/27606883-e7d86730-5b4f-11e7-83a2-3a687cf3e164.png)

![screen shot 2017-06-27 at 3 36 25 pm](https://user-images.githubusercontent.com/21222704/27606885-e985aa70-5b4f-11e7-93e3-b20efe67fd2f.png)

**Comment by floresj** [comment] 2017-06-28 12:55
Good catch! I'm updating the placeholder text for Country. However, I don't think I'm following what the issue is with the fields.

**Comment by bmallred** [comment] 2017-06-28 13:04
I think I evaluate this to the form of:

```
Location = City + ((State + Zip Code) or (Country))
```

So for domestic locations

```
Location = City + State + Zip Code
```

and for non-domestic

```
Location = City + Country
```

![screen shot 2017-06-13 at 4 01 18 pm](https://user-images.githubusercontent.com/19935974/27102222-70d2e7ee-5052-11e7-9d95-e8b5d7da04dc.png)

**Comment by billy22g** [comment] 2017-06-29 13:25
Yes, that's exactly right @bmallred. I think it's just poorly worded, which caused the initial confusion. For outside the U.S. it should just be city + country.

@floresj I'm still seeing the incorrect placeholder text though. Looks like may not be merged yet?

<img width="640" alt="screen shot 2017-06-29 at 7 24 12 am" src="https://user-images.githubusercontent.com/5091167/27689633-112b77a6-5c9c-11e7-8f9a-af3b995eaec5.png">

**Comment by billy22g** [comment] 2017-06-30 04:17
Yep, that's right! And sounds good to me re: the placeholder, thanks.

**Comment by colinpmacarthur** [comment] 2017-07-07 21:29
I just took another look at this one and it looks like all of the above issues have been fixed. However, I noticed a typo in the placeholder of the US address screen:

![screen shot 2017-07-07 at 5 27 12 pm](https://user-images.githubusercontent.com/2092076/27977669-cee4b480-6339-11e7-96ec-fbf1f23bea0c.png)

We should probably add a space between "Zip" and "code" ?

**Comment by billy22g** [comment] 2017-07-07 21:43
+1

**Comment by Jay-Neighbours-I72** [comment] 2017-07-10 16:01
Agreed, should also match the capitalization we decided on a while ago "ZIP Code"

**Comment by bmallred** [comment] 2017-07-10 17:02
These references have been updated and should be up on staging soon!

**Comment by colinpmacarthur** [comment] 2017-07-10 18:20
LGTM! I think we can move this issue to Done.

**Closed** 2017-07-10 18:20 UTC
Labels: bug
