### ISSUE TITLE
All sections - accordions

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2138] opened 2017-10-31 18:06 UTC
- [x] When coming back to a section all accordions with more than one item should load closed

(seen in Relatives section)

**Comment by bmallred** [comment] 2017-10-31 19:56
Duplicate of #1933, #1321, #1976

**Comment by Jay-Neighbours-I72** [comment] 2017-11-01 14:13
Direction:
- [ ] User comes back to a section with a single accordion item = Accordion item is open
- [ ] User comes back to a section with multiple accordion items = Accordion items are closed

**Closed** 2017-11-21 23:20 UTC
Labels: bug, duplicate, usability

**Comment by Jay-Neighbours-I72** [comment] 2017-11-27 14:43
lgtm
