### ISSUE TITLE
Military history - Foreign military - multiple inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1348] opened 2017-05-31 15:04 UTC
Added 2 instances of a foreign military

On the third instance inputs are not validation and buttons can't be clicked

<img width="1225" alt="screen shot 2017-05-31 at 11 03 41 am" src="https://cloud.githubusercontent.com/assets/19935974/26638726/dcd4a318-45f0-11e7-933d-531a22912aae.png">

**Comment by bmallred** [comment] 2017-06-05 15:11
This may have been resolved indirectly. Unable to reproduce (tested 5 items)

**Closed by bmallred** 2017-06-05 15:11 UTC
Labels: bug

**Comment by billy22g** [comment] 2017-06-05 23:21
LGTM
