### ISSUE TITLE
Accordion closed when coming back to a section

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1933] opened 2017-09-14 19:46 UTC
- [x] Let's load all accordions closed when returning to a section. 

This way when users come back to a section with a lot of accordion items it is easier to find what they are looking for.

**Comment by bmallred** [comment] 2017-09-15 13:47
Duplicate of #1321 

This is the end goal, but currently not capable of doing so since there wasn't a way to tell if based on the state of the data. I think when @floresj has pushed up all the changes for the **incomplete** messages we will have a better chance of implementing this.

**Closed** 2017-11-21 23:20 UTC
Labels: bug, duplicate

**Comment by Jay-Neighbours-I72** [comment] 2017-11-27 17:38
lgtm
