### ISSUE TITLE
Emotional health - reduce space between name and phone

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1133] opened 2017-05-04 15:29 UTC
- [x] For caregiver info and agency info blocks - reduce margin between name and phone block

Prototype:
<img width="1027" alt="screen shot 2017-05-04 at 11 26 25 am" src="https://cloud.githubusercontent.com/assets/19935974/25711449/ee55680a-30bc-11e7-9201-16f7914ea357.png">

-

Desired:
<img width="983" alt="screen shot 2017-05-04 at 11 28 23 am" src="https://cloud.githubusercontent.com/assets/19935974/25711460/f624434e-30bc-11e7-900d-03477f2f459c.png">

**Comment by bmallred** [comment] 2017-05-04 15:41
Duplicate of #1115

**Comment by billy22g** [comment] 2017-05-05 18:41
LGTM

**Closed** 2017-05-05 20:19 UTC
Labels: bug, duplicate
