### ISSUE TITLE
Phone numbers - DSN/Outside US links

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2667] opened 2018-02-23 15:54 UTC
- [ ] Phone number switching links should say "Switch to DSN, Switch to..." for screen readers

**Comment by bmallred** [comment] 2018-03-21 18:22
@Jay-Neighbours-I72 is this a duplicate of https://github.com/truetandem/e-QIP-prototype/issues/2739

**Closed** 2018-03-22 19:23 UTC
Labels: accessibility, duplicate, high

**Comment by Jay-Neighbours-I72** [comment] 2018-04-09 17:33
lgtm
