### ISSUE TITLE
Constantly getting Kicked out of the Application

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2505] opened 2018-01-25 17:41 UTC
**What did you do?**
Click on a field/section/next section
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
The application to take the user to the field/section/next section (whichever user clicked on)
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
Kicked out of application
*Include a high-level description of the feature or error here*
Getting kicked out 4-5 times an hour, when logged back in, much of the data is missing and I have to re-enter it. 
**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

 - What browser and version are you using?
Google Chrome

 - What operating system?
Windows 7

**Comment by bmallred** [comment] 2018-01-26 13:50
Having trouble reproducing this but is definitely being reported by multiple individuals on other networks.

**Comment by bmallred** [comment] 2018-03-12 16:01
This may have been resolved with #2704. Going to keep this open for a bit longer to see if any updates to this come in.

**Comment by bmallred** [comment] 2018-03-21 11:56
Closing this since it seems to have been resolved. Can re-open if problem arises again!

**Closed by bmallred** 2018-03-21 11:56 UTC
Labels: bug, high
