### ISSUE TITLE
Separate form instructions from legal information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1985] opened 2017-09-27 16:37 UTC
As an eApp applicant I want to see the form instructions separately from the form legal information when I log into the form so that the form instruction information is more prominently displayed and I am more likely to read it.

Acceptance Criteria
- [x] The eApp designer guides the design
- [x] The form information appears in separate section from the legal information

**Comment by Jay-Neighbours-I72** [comment] 2017-09-28 15:44
Maybe wrap this one in as well #1963

**Comment by Jay-Neighbours-I72** [comment] 2017-10-04 15:54
Proposed idea:
![2017-10-04](https://user-images.githubusercontent.com/19935974/31185707-a75aeb76-a8fa-11e7-92ac-a8b2c2373e14.png)

The goal here is a more natural flow while pushing the instructions to the top. User reads title, brief sentence about instructions, full instructions, then gets to all the legal text.

**Comment by lauraponce** [comment] 2017-10-05 15:46
@Jay-Neighbours-I72 this looks great and feels like a natural separation of the instructional content vs legal content.

**Comment by lauraponce** [comment] 2017-10-06 18:38
Should the instructions text be sentence case instead of title case? "Instructions for completing this form" instead of "Instructions for Completing this Form" I feel like we have been opting for sentence case unless it's the actual formal title of something on the form.

Also, there is some extra padding before the "Purpose of this form" section – is that by design @Jay-Neighbours-I72? 
<img width="909" alt="screen shot 2017-10-06 at 2 36 40 pm" src="https://user-images.githubusercontent.com/21222704/31293084-e578ea84-aaa3-11e7-83a7-ef1110dd1ad7.png">

**Comment by Jay-Neighbours-I72** [comment] 2017-10-09 13:05
@lauraponce I agree on sentence case, that will be more consistent. I can do a PR for this

That extra margin looks like it has been fixed:
<img width="1959" alt="screen shot 2017-10-09 at 9 04 46 am" src="https://user-images.githubusercontent.com/19935974/31339467-f298c37c-acd0-11e7-97c4-6c27f746cfd1.png">

**Comment by bmallred** [comment] 2017-10-10 20:35
Going to close this. If there are still issues (changes should be online now) please feel free to open!

**Closed by bmallred** 2017-10-10 20:35 UTC
Labels: Epic, points-5
