### ISSUE TITLE
Emotional Health - review screen intro

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1131] opened 2017-05-04 15:08 UTC
- [ ] This section is missing the review screen intro text

<img width="1576" alt="screen shot 2017-05-04 at 11 07 41 am" src="https://cloud.githubusercontent.com/assets/19935974/25710339/f86814bc-30b9-11e7-8984-9dc37b181d46.png">

Intro text example
<img width="1311" alt="screen shot 2017-05-04 at 11 06 52 am" src="https://cloud.githubusercontent.com/assets/19935974/25710347/fdf1acd6-30b9-11e7-9e37-aa98cb92277d.png">

**Comment by bmallred** [comment] 2017-05-04 15:40
Duplicate of #1113

**Comment by billy22g** [comment] 2017-05-05 18:34
LGTM

**Closed** 2017-05-05 20:21 UTC
Labels: bug, duplicate
