### ISSUE TITLE
Your history - review screen - Contact info block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1975] opened 2017-09-25 20:22 UTC
Where you have lived - contact block:

- [x] When "I don't know" is selected the review screen is giving a required error.

<img width="891" alt="screen shot 2017-09-25 at 4 20 46 pm" src="https://user-images.githubusercontent.com/19935974/30829037-a6004792-a20d-11e7-86ee-90814400f480.png">

**Comment by bmallred** [comment] 2018-01-09 16:15
Duplicate of #2310

**Closed** 2018-01-09 18:32 UTC
Labels: bug, duplicate, medium

**Comment by Jay-Neighbours-I72** [comment] 2018-01-11 20:51
lgtm
