### ISSUE TITLE
Foreign passports - expiration date - wrong error message

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2407] opened 2018-01-15 18:51 UTC
- [x] Wrong error message showing for expiration date validation

![screen shot 2018-01-15 at 1 49 49 pm](https://user-images.githubusercontent.com/19935974/34957337-34c74f76-f9fb-11e7-98fd-a4ea2540dce2.jpg)

**Comment by bmallred** [comment] 2018-02-13 19:25
Duplicate of #2526

**Closed by bmallred** 2018-02-13 19:25 UTC
Labels: bug, duplicate, high

**Comment by Jay-Neighbours-I72** [comment] 2018-02-21 16:46
lgtm
