### ISSUE TITLE
Section 5 - Dual Citizenship - Missing question

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1827] opened 2017-08-24 15:23 UTC
Do you currently hold citizenship with this country is missing.
![dual](https://user-images.githubusercontent.com/30842622/29673948-bc3e6074-88be-11e7-9cee-58b520969f73.png)

**Comment by Jay-Neighbours-I72** [comment] 2017-09-12 17:25
@bmallred @floresj Looks like the Present/Current branch isn't loading when "Present" is selected in date range.

![screen shot 2017-09-12 at 1 24 29 pm](https://user-images.githubusercontent.com/19935974/30339676-cfcf5888-97bd-11e7-9185-47877a8246f3.png)

**Comment by bmallred** [comment] 2017-09-18 19:11
Reference: https://github.com/truetandem/e-QIP-prototype/issues/1642#issuecomment-321039441

**Comment by bmallred** [comment] 2017-12-05 03:32
ping @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment] 2017-12-05 15:19
This looks good to me now. Closing

**Comment by billy22g** [comment] 2017-12-27 20:38
Nothing is loading when I select "Yes" for this top-level question.

<img width="797" alt="screen shot 2017-12-27 at 1 37 09 pm" src="https://user-images.githubusercontent.com/5091167/34392706-209e797e-eb0b-11e7-8180-507b9b50b1bb.png">

**Comment by Jay-Neighbours-I72** [comment] 2018-01-02 14:36
I'm seeing that now too^

**Comment by bmallred** [comment] 2018-01-02 21:12
Not seeing this on **dev**. Will probably have to get w/ @Jay-Neighbours-I72 to see how to reproduce

![image](https://user-images.githubusercontent.com/697855/34500185-a09b2f2a-efd7-11e7-931a-bf9fa7cbf46b.png)

**Comment by Jay-Neighbours-I72** [comment] 2018-01-02 21:14
cleared cache today, testing again and i'm seeing the branch open now

**Comment by bmallred** [comment] 2018-01-02 21:16
@Jay-Neighbours-I72 @billy22g cool, yeah so **dev** not seeing this behavior, but was able to reproduce it twice on **staging**. Taking a look!

**Comment by billy22g** [comment] 2018-01-02 21:17
Thanks folks! :high-five:

________________________________

**Comment by bmallred** [comment] 2018-01-02 21:33
@billy22g quick experiment (no rush) but I think if you:

 1. Go to the section
 2. Select "no"
 3. Accept the browser confirmation
 4. Click "save"
 5. Log out and clear cache and log in (or just try launching via a private/incognito window)

Does that work? It appears in https://github.com/truetandem/e-QIP-prototype/commit/4e4e5f386f6779963213b22bfd2d35bc3364567b the property names were updated and so if old information was saved it may be conflicting.

**Comment by bmallred** [comment] 2018-01-18 13:49
ping @billy22g

**Comment by floresj** [comment] 2018-01-19 18:58
That branch opens up with the latest from master.
![selection_662](https://user-images.githubusercontent.com/5938731/35166718-d6a1df96-fd20-11e7-832d-67c3946a0e11.png)

**Closed** 2018-01-19 21:05 UTC
Labels: bug, high

**Comment by Jay-Neighbours-I72** [comment] 2018-02-21 18:53
working for me too

![screen shot 2018-02-21 at 1 53 21 pm](https://user-images.githubusercontent.com/19935974/36499224-9b792af2-170e-11e8-8c37-66493dea1899.jpg)

**Comment by pjsumm** [comment] 2018-03-14 14:13
all branching in the history of this issue is behaving as expected in both dev and staging.
