### ISSUE TITLE
Investigations and clearance record > Ever been investigated - deselect functionality

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1958] opened 2017-09-20 15:00 UTC
- [ ] Switching an answer to "I don't know" should remove the previous selection
- [ ] Users should not be able to click on the greyed out buttons when "I don't know" is selected

<img width="1218" alt="screen shot 2017-09-20 at 10 04 27 am" src="https://user-images.githubusercontent.com/19935974/30648056-1c2ae26e-9deb-11e7-9755-ffc8a7e21c62.png">

**Comment by bmallred** [comment] 2017-11-30 16:37
Duplicate of https://github.com/truetandem/e-QIP-prototype/issues/1800

**Closed by bmallred** 2017-11-30 16:37 UTC
Labels: bug, duplicate

**Comment by Jay-Neighbours-I72** [comment] 2017-12-20 17:43
lgtm
