### ISSUE TITLE
Your history - accordion closed when returning

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1976] opened 2017-09-25 20:24 UTC
On individual Your History sections (Where you have lived, etc) when a user returns all accordion items should be closed. (This should be the functionality form wide too)

**Comment by bmallred** [comment] 2017-10-31 19:56
Duplicate of #1933, #1321, #2138

**Closed** 2017-11-21 23:21 UTC
Labels: bug, duplicate
