### ISSUE TITLE
Reuse address function - not showing valid

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2274] opened 2017-12-04 18:51 UTC
- [x] When using a previously used address the inputs are not getting the green valid style

![screen shot 2017-12-04 at 1 49 28 pm](https://user-images.githubusercontent.com/19935974/33570224-28183078-d8fa-11e7-8537-d021472d3df4.jpg)

**Comment by bmallred** [comment] 2018-01-12 19:49
Duplicate of #2086

**Closed** 2018-01-16 19:44 UTC
Labels: bug, duplicate, high

**Comment by Jay-Neighbours-I72** [comment] 2018-02-21 19:19
lgtm
