### ISSUE TITLE
Spouses DOB

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2494] opened 2018-01-24 19:18 UTC
**What did you do?**
Provided a DOB for spouse. DOB was before applicant's birthdate.  Received an error message stating my spouse's date should be after **Your** date of birth
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
No error message.
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
Spouse does not have to be older than applicant.  
**What did you see instead?**
An error message stating date s/b AFTER your date of birth.
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35352246-5b3b208e-0111-11e8-86b7-7c42290781b8.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment] 2018-02-15 15:50
Duplicate of #2402

Looks like this has been fixed, I'm not seeing the error (DOB 1980 in this example)

![screen shot 2018-02-15 at 10 49 43 am](https://user-images.githubusercontent.com/19935974/36265812-07063f06-123e-11e8-81a6-5bf36ee3f3aa.jpg)

**Closed** 2018-02-15 15:51 UTC
