### ISSUE TITLE
Foreign business > Employment

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2233] opened 2017-11-22 17:17 UTC
- [ ] Close gap between "accept offer" and explanation

![screen shot 2017-11-22 at 12 16 57 pm](https://user-images.githubusercontent.com/19935974/33140820-238a5b0a-cf7f-11e7-96d4-0f9b631cd78f.png)

**Comment by floresj** [comment] 2018-01-31 22:02
Duplicate of #2540. Closing this one.

**Closed by floresj** 2018-01-31 22:02 UTC
Labels: bug, duplicate, low

**Comment by lauraponce** [comment] 2018-02-05 16:11
#2540 was resolved
