### ISSUE TITLE
Emotional health - some address blocks appear not to be validating

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1031] opened 2017-04-25 14:39 UTC
- [ ] Address blocks are not validating and giving the USPS suggestion.

(Hospitalization works, second address input didn’t)

![screen shot 2017-04-25 at 10 38 17 am](https://cloud.githubusercontent.com/assets/26907482/25391070/5b0f1ab6-29a3-11e7-8610-d5dc4d5519b4.png)

**Comment by bmallred** [comment] 2017-04-28 13:56
@gabesnyder not able to reproduce. Is this still happening on your end?

## What I am seeing

![validation-working](https://cloud.githubusercontent.com/assets/697855/25531782/e55664c0-2bf8-11e7-85f2-2b507c38673d.png)

**Comment by floresj** [comment] 2017-05-08 18:07
@gabesnyder @Jay-Neighbours-I72 Is this still an issue?

**Comment by floresj** [comment] 2017-05-08 18:31
I think I may be able to reproduce. Going to take a closer look.

**Comment by billy22g** [comment] 2017-05-09 22:20
I was able to reproduce, just put an issue in for similar thing. #1187

**Comment by billy22g** [comment] 2017-05-10 18:57
Working now but seems maybe intermittent.

**Comment by bmallred** [comment] 2017-06-15 13:07
Moving this in to review since unable to reproduce and similar issues have been resolved.

**Closed by bmallred** 2017-06-15 13:07 UTC
Labels: bug

**Comment by billy22g** [comment] 2017-06-15 22:28
I think this was resolved with the latest validation fixes. Thanks @bmallred!
